# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Objcoder
tagline: "My dev random rant"
description: > # this means to ignore newlines until "baseurl:"
  Random rant on my daily software development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sergioutama.github.io" # the base hostname & protocol for your site
paginate: 1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

twitter_username: sergioutama
github_username:  sergioutama

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
